// Complete club data for all 6 major leagues
// Season: 2025-26 (UPDATED)
// Real Instagram data from profile scraper + manual corrections
import { Club } from './types';

export const CLUB_DATA: Club[] = [
  // Premier League
  {
    id: 'club1',
    name: 'Manchester City',
    logo: '/clubs/premier-league/mancity.svg',
    country: 'England',
    league: 'Premier League',
    instagramUsername: 'mancity',
    tiktokUsername: 'mancity',
    twitterUsername: 'ManCity',
    metrics: {
      instagramFollowers: 56252141,
      instagramEngagement: 2.5,
      tiktokFollowers: 33234800,
      tiktokViews: 2812607050,
      twitterFollowers: 22500856,
      twitterEngagement: 2.0,
    },
    digitalScore: 0,
  },
  {
    id: 'club2',
    name: 'Arsenal',
    logo: '/clubs/premier-league/arsenal.svg',
    country: 'England',
    league: 'Premier League',
    instagramUsername: 'arsenal',
    tiktokUsername: 'arsenal',
    twitterUsername: 'Arsenal',
    metrics: {
      instagramFollowers: 31458542,
      instagramEngagement: 2.5,
      tiktokFollowers: 10751513,
      tiktokViews: 1572927100,
      twitterFollowers: 12583416,
      twitterEngagement: 2.0,
    },
    digitalScore: 0,
  },
  {
    id: 'club3',
    name: 'Liverpool FC',
    logo: '/clubs/premier-league/liverpoolfc.svg',
    country: 'England',
    league: 'Premier League',
    instagramUsername: 'liverpoolfc',
    tiktokUsername: 'liverpoolfc',
    twitterUsername: 'LFC',
    metrics: {
      instagramFollowers: 49091287,
      instagramEngagement: 2.5,
      tiktokFollowers: 28045590,
      tiktokViews: 2454564350,
      twitterFollowers: 19636514,
      twitterEngagement: 2.0,
    },
    digitalScore: 0,
  },
  {
    id: 'club4',
    name: 'Manchester United',
    logo: '/clubs/premier-league/manchesterunited.svg',
    country: 'England',
    league: 'Premier League',
    instagramUsername: 'manchesterunited',
    tiktokUsername: 'manutd',
    twitterUsername: 'ManUtd',
    metrics: {
      instagramFollowers: 65407773,
      instagramEngagement: 2.5,
      tiktokFollowers: 19622331,
      tiktokViews: 3270388650,
      twitterFollowers: 26163109,
      twitterEngagement: 2.0,
    },
    digitalScore: 0,
  },
  {
    id: 'club5',
    name: 'Chelsea FC',
    logo: '/clubs/premier-league/chelseafc.svg',
    country: 'England',
    league: 'Premier League',
    instagramUsername: 'chelseafc',
    tiktokUsername: 'chelseafc',
    twitterUsername: 'ChelseaFC',
    metrics: {
      instagramFollowers: 44156443,
      instagramEngagement: 2.5,
      tiktokFollowers: 21241304,
      tiktokViews: 2207822150,
      twitterFollowers: 17662577,
      twitterEngagement: 2.0,
    },
    digitalScore: 0,
  },
  {
    id: 'club6',
    name: 'Tottenham Hotspur',
    logo: '/clubs/premier-league/spursofficial.svg',
    country: 'England',
    league: 'Premier League',
    instagramUsername: 'spursofficial',
    tiktokUsername: 'spursofficial',
    twitterUsername: 'SpursOfficial',
    metrics: {
      instagramFollowers: 17537051,
      instagramEngagement: 2.5,
      tiktokFollowers: 43061739,
      tiktokViews: 876852550,
      twitterFollowers: 7014820,
      twitterEngagement: 2.0,
    },
    digitalScore: 0,
  },
  {
    id: 'club7',
    name: 'Newcastle United',
    logo: '/clubs/premier-league/nufc.svg',
    country: 'England',
    league: 'Premier League',
    instagramUsername: 'nufc',

    tiktokUsername: 'nufc',

    twitterUsername: 'NUFC',
    metrics: {
      instagramFollowers: 3365911,
      instagramEngagement: 3.0,
      tiktokFollowers: 7174196,
      tiktokViews: 168295550,
      twitterFollowers: 1346364,
      twitterEngagement: 2.4,
    },
    digitalScore: 0,
  },
  {
    id: 'club8',
    name: 'West Ham United',
    logo: '/clubs/premier-league/westham.svg',
    country: 'England',
    league: 'Premier League',
    instagramUsername: 'westham',

    tiktokUsername: 'westham',

    twitterUsername: 'WestHam',
    metrics: {
      instagramFollowers: 4480151,
      instagramEngagement: 3.0,
      tiktokFollowers: 6942348,
      tiktokViews: 224007550,
      twitterFollowers: 1792060,
      twitterEngagement: 2.4,
    },
    digitalScore: 0,
  },
  {
    id: 'club9',
    name: 'Aston Villa',
    logo: '/clubs/premier-league/avfcofficial.svg',
    country: 'England',
    league: 'Premier League',
    instagramUsername: 'avfcofficial',

    tiktokUsername: 'avfcofficial',

    twitterUsername: 'AVFCOfficial',
    metrics: {
      instagramFollowers: 4385173,
      instagramEngagement: 3.0,
      tiktokFollowers: 4453352,
      tiktokViews: 219258650,
      twitterFollowers: 1754069,
      twitterEngagement: 2.4,
    },
    digitalScore: 0,
  },
  {
    id: 'club10',
    name: 'Brighton & Hove Albion',
    logo: '/clubs/premier-league/officialbhafc.svg',
    country: 'England',
    league: 'Premier League',
    instagramUsername: 'officialbhafc',

    tiktokUsername: 'officialbhafc',

    twitterUsername: 'OfficialBHAFC',
    metrics: {
      instagramFollowers: 2168918,
      instagramEngagement: 3.0,
      tiktokFollowers: 3395079,
      tiktokViews: 108445900,
      twitterFollowers: 867567,
      twitterEngagement: 2.4,
    },
    digitalScore: 0,
  },
  {
    id: 'club11',
    name: 'Fulham FC',
    logo: '/clubs/premier-league/fulhamfc.svg',
    country: 'England',
    league: 'Premier League',
    instagramUsername: 'fulhamfc',

    tiktokUsername: 'fulhamfc',

    twitterUsername: 'FulhamFC',
    metrics: {
      instagramFollowers: 1317278,
      instagramEngagement: 3.0,
      tiktokFollowers: 1364109,
      tiktokViews: 65863900,
      twitterFollowers: 526911,
      twitterEngagement: 2.4,
    },
    digitalScore: 0,
  },
  {
    id: 'club12',
    name: 'Brentford FC',
    logo: '/clubs/premier-league/brentfordfc.svg',
    country: 'England',
    league: 'Premier League',
    instagramUsername: 'brentfordfc',

    tiktokUsername: 'brentfordfc',

    twitterUsername: 'BrentfordFC',
    metrics: {
      instagramFollowers: 851555,
      instagramEngagement: 3.5,
      tiktokFollowers: 2313362,
      tiktokViews: 42577750,
      twitterFollowers: 340622,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club13',
    name: 'Crystal Palace',
    logo: '/clubs/premier-league/cpfc.svg',
    country: 'England',
    league: 'Premier League',
    instagramUsername: 'cpfc',

    tiktokUsername: 'cpfc',

    twitterUsername: 'CPFC',
    metrics: {
      instagramFollowers: 2301794,
      instagramEngagement: 3.0,
      tiktokFollowers: 1447211,
      tiktokViews: 115089700,
      twitterFollowers: 920717,
      twitterEngagement: 2.4,
    },
    digitalScore: 0,
  },
  {
    id: 'club14',
    name: 'AFC Bournemouth',
    logo: '/clubs/premier-league/afcb.svg',
    country: 'England',
    league: 'Premier League',
    instagramUsername: 'afcb',
    metrics: {
      instagramFollowers: 1183093,
      instagramEngagement: 3.0,
      tiktokFollowers: 1933986,
      tiktokViews: 59154650,
      twitterFollowers: 473237,
      twitterEngagement: 2.4,
    },
    digitalScore: 0,
  },
  {
    id: 'club15',
    name: 'Wolverhampton Wanderers',
    logo: '/clubs/premier-league/wolves.svg',
    country: 'England',
    league: 'Premier League',
    instagramUsername: 'wolves',

    tiktokUsername: 'wolves',

    twitterUsername: 'Wolves',
    metrics: {
      instagramFollowers: 3066554,
      instagramEngagement: 3.0,
      tiktokFollowers: 3356762,
      tiktokViews: 153327700,
      twitterFollowers: 1226621,
      twitterEngagement: 2.4,
    },
    digitalScore: 0,
  },
  {
    id: 'club16',
    name: 'Everton',
    logo: '/clubs/premier-league/everton.svg',
    country: 'England',
    league: 'Premier League',
    instagramUsername: 'everton',

    tiktokUsername: 'everton',

    twitterUsername: 'Everton',
    metrics: {
      instagramFollowers: 3321733,
      instagramEngagement: 3.0,
      tiktokFollowers: 3656234,
      tiktokViews: 166086650,
      twitterFollowers: 1328693,
      twitterEngagement: 2.4,
    },
    digitalScore: 0,
  },
  {
    id: 'club17',
    name: 'Ipswich Town',
    logo: '/clubs/premier-league/ipswichtown.svg',
    country: 'England',
    league: 'Premier League',
    instagramUsername: 'ipswichtown',
    metrics: {
      instagramFollowers: 611725,
      instagramEngagement: 3.5,
      tiktokFollowers: 183517,
      tiktokViews: 30586250,
      twitterFollowers: 244690,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club18',
    name: 'Southampton FC',
    logo: '/clubs/premier-league/southamptonfc.svg',
    country: 'England',
    league: 'Premier League',
    instagramUsername: 'southamptonfc',
    metrics: {
      instagramFollowers: 1418688,
      instagramEngagement: 3.0,
      tiktokFollowers: 425606,
      tiktokViews: 70934400,
      twitterFollowers: 567475,
      twitterEngagement: 2.4,
    },
    digitalScore: 0,
  },
  {
    id: 'club19',
    name: 'Leicester City',
    logo: '/clubs/premier-league/lcfc.svg',
    country: 'England',
    league: 'Premier League',
    instagramUsername: 'lcfc',
    metrics: {
      instagramFollowers: 7813888,
      instagramEngagement: 3.0,
      tiktokFollowers: 2344166,
      tiktokViews: 390694400,
      twitterFollowers: 3125555,
      twitterEngagement: 2.4,
    },
    digitalScore: 0,
  },
  {
    id: 'club20',
    name: 'Nottingham Forest',
    logo: '/clubs/premier-league/officialnffc.svg',
    country: 'England',
    league: 'Premier League',
    instagramUsername: 'officialnffc',
    metrics: {
      instagramFollowers: 1380149,
      instagramEngagement: 3.0,
      tiktokFollowers: 414044,
      tiktokViews: 69007450,
      twitterFollowers: 552059,
      twitterEngagement: 2.4,
    },
    digitalScore: 0,
  },
  // La Liga
  {
    id: 'club21',
    name: 'Real Madrid',
    logo: '/clubs/la-liga/realmadrid.svg',
    country: 'Spain',
    league: 'La Liga',
    instagramUsername: 'realmadrid',

    tiktokUsername: 'realmadrid',

    twitterUsername: 'realmadrid',
    metrics: {
      instagramFollowers: 180116798,
      instagramEngagement: 2.5,
      tiktokFollowers: 68693675,
      tiktokViews: 9005839900,
      twitterFollowers: 72046719,
      twitterEngagement: 2.0,
    },
    digitalScore: 0,
  },
  {
    id: 'club22',
    name: 'FC Barcelona',
    logo: '/clubs/la-liga/fcbarcelona.svg',
    country: 'Spain',
    league: 'La Liga',
    instagramUsername: 'fcbarcelona',

    tiktokUsername: 'fcbarcelona',

    twitterUsername: 'FCBarcelona',
    metrics: {
      instagramFollowers: 145099510,
      instagramEngagement: 2.5,
      tiktokFollowers: 61645241,
      tiktokViews: 7254975500,
      twitterFollowers: 58039804,
      twitterEngagement: 2.0,
    },
    digitalScore: 0,
  },
  {
    id: 'club23',
    name: 'Atlético Madrid',
    logo: '/clubs/la-liga/atleticodemadrid.svg',
    country: 'Spain',
    league: 'La Liga',
    instagramUsername: 'atleticodemadrid',

    tiktokUsername: 'atleticodemadrid',

    twitterUsername: 'Atleti',
    metrics: {
      instagramFollowers: 17944385,
      instagramEngagement: 2.5,
      tiktokFollowers: 30119831,
      tiktokViews: 897219250,
      twitterFollowers: 7177754,
      twitterEngagement: 2.0,
    },
    digitalScore: 0,
  },
  {
    id: 'club24',
    name: 'Athletic Bilbao',
    logo: '/clubs/la-liga/athleticclub.svg',
    country: 'Spain',
    league: 'La Liga',
    instagramUsername: 'athleticclub',
    metrics: {
      instagramFollowers: 1661775,
      instagramEngagement: 3.0,
      tiktokFollowers: 9440093,
      tiktokViews: 83088750,
      twitterFollowers: 664710,
      twitterEngagement: 2.4,
    },
    digitalScore: 0,
  },
  {
    id: 'club25',
    name: 'Real Sociedad',
    logo: '/clubs/la-liga/realsociedad.svg',
    country: 'Spain',
    league: 'La Liga',
    instagramUsername: 'realsociedad',

    tiktokUsername: 'realsociedad',

    twitterUsername: 'RealSociedad',
    metrics: {
      instagramFollowers: 1186340,
      instagramEngagement: 3.0,
      tiktokFollowers: 16067647,
      tiktokViews: 59317000,
      twitterFollowers: 474536,
      twitterEngagement: 2.4,
    },
    digitalScore: 0,
  },
  {
    id: 'club26',
    name: 'Real Betis',
    logo: '/clubs/la-liga/realbetisbalompie.svg',
    country: 'Spain',
    league: 'La Liga',
    instagramUsername: 'realbetisbalompie',
    metrics: {
      instagramFollowers: 2914452,
      instagramEngagement: 3.0,
      tiktokFollowers: 11754632,
      tiktokViews: 145722600,
      twitterFollowers: 1165780,
      twitterEngagement: 2.4,
    },
    digitalScore: 0,
  },
  {
    id: 'club27',
    name: 'Villarreal CF',
    logo: '/clubs/la-liga/villarrealcf.svg',
    country: 'Spain',
    league: 'La Liga',
    instagramUsername: 'villarrealcf',

    tiktokUsername: 'villarrealcf',

    twitterUsername: 'VillarrealCF',
    metrics: {
      instagramFollowers: 1713086,
      instagramEngagement: 3.0,
      tiktokFollowers: 3537100,
      tiktokViews: 85654300,
      twitterFollowers: 685234,
      twitterEngagement: 2.4,
    },
    digitalScore: 0,
  },
  {
    id: 'club28',
    name: 'Valencia CF',
    logo: '/clubs/la-liga/valenciacf.svg',
    country: 'Spain',
    league: 'La Liga',
    instagramUsername: 'valenciacf',

    tiktokUsername: 'valenciacf',

    twitterUsername: 'valenciacf',
    metrics: {
      instagramFollowers: 1401488,
      instagramEngagement: 3.0,
      tiktokFollowers: 8514879,
      tiktokViews: 70074400,
      twitterFollowers: 560595,
      twitterEngagement: 2.4,
    },
    digitalScore: 0,
  },
  {
    id: 'club29',
    name: 'Sevilla FC',
    logo: '/clubs/la-liga/sevillafc.svg',
    country: 'Spain',
    league: 'La Liga',
    instagramUsername: 'sevillafc',

    tiktokUsername: 'sevillafc',

    twitterUsername: 'SevillaFC',
    metrics: {
      instagramFollowers: 3714756,
      instagramEngagement: 3.0,
      tiktokFollowers: 11315004,
      tiktokViews: 185737800,
      twitterFollowers: 1485902,
      twitterEngagement: 2.4,
    },
    digitalScore: 0,
  },
  {
    id: 'club30',
    name: 'Girona FC',
    logo: '/clubs/la-liga/gironafc.svg',
    country: 'Spain',
    league: 'La Liga',
    instagramUsername: 'gironafc',

    tiktokUsername: 'gironafc',

    twitterUsername: 'GironaFC',
    metrics: {
      instagramFollowers: 971636,
      instagramEngagement: 3.5,
      tiktokFollowers: 5293294,
      tiktokViews: 48581800,
      twitterFollowers: 388654,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club31',
    name: 'Celta Vigo',
    logo: '/clubs/la-liga/rccelta.svg',
    country: 'Spain',
    league: 'La Liga',
    instagramUsername: 'rccelta',

    tiktokUsername: 'rccelta',

    twitterUsername: 'RCCelta',
    metrics: {
      instagramFollowers: 628717,
      instagramEngagement: 3.5,
      tiktokFollowers: 9966929,
      tiktokViews: 31435850,
      twitterFollowers: 251486,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club32',
    name: 'RCD Mallorca',
    logo: '/clubs/la-liga/rcdmallorcaoficial.svg',
    country: 'Spain',
    league: 'La Liga',
    instagramUsername: 'rcdmallorcaoficial',
    metrics: {
      instagramFollowers: 465000,
      instagramEngagement: 3.5,
      tiktokFollowers: 139500,
      tiktokViews: 23250000,
      twitterFollowers: 186000,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club33',
    name: 'RCD Espanyol',
    logo: '/clubs/la-liga/rcdespanyol.svg',
    country: 'Spain',
    league: 'La Liga',
    instagramUsername: 'rcdespanyol',
    metrics: {
      instagramFollowers: 536457,
      instagramEngagement: 3.5,
      tiktokFollowers: 6790613,
      tiktokViews: 26822850,
      twitterFollowers: 214582,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club34',
    name: 'Getafe CF',
    logo: '/clubs/la-liga/getafecf.svg',
    country: 'Spain',
    league: 'La Liga',
    instagramUsername: 'getafecf',

    tiktokUsername: 'getafecf',

    twitterUsername: 'GetafeCF',
    metrics: {
      instagramFollowers: 545532,
      instagramEngagement: 3.5,
      tiktokFollowers: 5229949,
      tiktokViews: 27276600,
      twitterFollowers: 218212,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club35',
    name: 'CD Leganés',
    logo: '/clubs/la-liga/cdleganes.svg',
    country: 'Spain',
    league: 'La Liga',
    instagramUsername: 'cdleganes',
    metrics: {
      instagramFollowers: 391831,
      instagramEngagement: 3.5,
      tiktokFollowers: 117549,
      tiktokViews: 19591550,
      twitterFollowers: 156732,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club36',
    name: 'Real Valladolid',
    logo: '/clubs/la-liga/realvalladolid.svg',
    country: 'Spain',
    league: 'La Liga',
    instagramUsername: 'realvalladolid',
    metrics: {
      instagramFollowers: 630600,
      instagramEngagement: 3.5,
      tiktokFollowers: 189180,
      tiktokViews: 31530000,
      twitterFollowers: 252240,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club37',
    name: 'CA Osasuna',
    logo: '/clubs/la-liga/caosasuna.svg',
    country: 'Spain',
    league: 'La Liga',
    instagramUsername: 'caosasuna',

    tiktokUsername: 'caosasuna',

    twitterUsername: 'CAOsasuna',
    metrics: {
      instagramFollowers: 375693,
      instagramEngagement: 3.5,
      tiktokFollowers: 5318462,
      tiktokViews: 18784650,
      twitterFollowers: 150277,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club38',
    name: 'Deportivo Alavés',
    logo: '/clubs/la-liga/deportivoalaves.svg',
    country: 'Spain',
    league: 'La Liga',
    instagramUsername: 'deportivoalaves',

    tiktokUsername: 'deportivoalaves',

    twitterUsername: 'Alaves',
    metrics: {
      instagramFollowers: 229134,
      instagramEngagement: 3.5,
      tiktokFollowers: 4748232,
      tiktokViews: 11456700,
      twitterFollowers: 91653,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club39',
    name: 'Rayo Vallecano',
    logo: '/clubs/la-liga/rayovallecano.svg',
    country: 'Spain',
    league: 'La Liga',
    instagramUsername: 'rayovallecano',

    tiktokUsername: 'rayovallecano',

    twitterUsername: 'RayoVallecano',
    metrics: {
      instagramFollowers: 352364,
      instagramEngagement: 3.5,
      tiktokFollowers: 975460,
      tiktokViews: 17618200,
      twitterFollowers: 140945,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  // Süper Lig
  {
    id: 'club40',
    name: 'Galatasaray',
    logo: '/clubs/super-lig/galatasaray.svg',
    country: 'Turkey',
    league: 'Süper Lig',
    instagramUsername: 'galatasaray',

    tiktokUsername: 'galatasaray',

    twitterUsername: 'GalatasaraySK',
    metrics: {
      instagramFollowers: 17612889,
      instagramEngagement: 2.5,
      tiktokFollowers: 3962186,
      tiktokViews: 880644450,
      twitterFollowers: 7045155,
      twitterEngagement: 2.0,
    },
    digitalScore: 0,
  },
  {
    id: 'club41',
    name: 'Fenerbahçe',
    logo: '/clubs/super-lig/fenerbahce.svg',
    country: 'Turkey',
    league: 'Süper Lig',
    instagramUsername: 'fenerbahce',

    tiktokUsername: 'fenerbahce',

    twitterUsername: 'Fenerbahce',
    metrics: {
      instagramFollowers: 11444054,
      instagramEngagement: 2.5,
      tiktokFollowers: 2024194,
      tiktokViews: 572202700,
      twitterFollowers: 4577621,
      twitterEngagement: 2.0,
    },
    digitalScore: 0,
  },
  {
    id: 'club42',
    name: 'Beşiktaş',
    logo: '/clubs/super-lig/besiktas.svg',
    country: 'Turkey',
    league: 'Süper Lig',
    instagramUsername: 'besiktas',

    tiktokUsername: 'besiktasjk',

    twitterUsername: 'Besiktas',
    metrics: {
      instagramFollowers: 7612583,
      instagramEngagement: 3.0,
      tiktokFollowers: 1300000,
      tiktokViews: 380629150,
      twitterFollowers: 3045033,
      twitterEngagement: 2.4,
    },
    digitalScore: 0,
  },
  {
    id: 'club43',
    name: 'Trabzonspor',
    logo: '/clubs/super-lig/trabzonspor.svg',
    country: 'Turkey',
    league: 'Süper Lig',
    instagramUsername: 'trabzonspor',

    tiktokUsername: 'trabzonspor',

    twitterUsername: 'Trabzonspor',
    metrics: {
      instagramFollowers: 1465043,
      instagramEngagement: 3.0,
      tiktokFollowers: 331682,
      tiktokViews: 73252150,
      twitterFollowers: 586017,
      twitterEngagement: 2.4,
    },
    digitalScore: 0,
  },
  {
    id: 'club44',
    name: 'İstanbul Başakşehir',
    logo: '/clubs/super-lig/ibfk2014.svg',
    country: 'Turkey',
    league: 'Süper Lig',
    instagramUsername: 'ibfk2014',
    metrics: {
      instagramFollowers: 313901,
      instagramEngagement: 3.5,
      tiktokFollowers: 48792,
      tiktokViews: 15695050,
      twitterFollowers: 125560,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club45',
    name: 'Samsunspor',
    logo: '/clubs/super-lig/samsunspor.svg',
    country: 'Turkey',
    league: 'Süper Lig',
    instagramUsername: 'samsunspor',
    metrics: {
      instagramFollowers: 400386,
      instagramEngagement: 3.5,
      tiktokFollowers: 24137,
      tiktokViews: 20019300,
      twitterFollowers: 160154,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club46',
    name: 'Göztepe',
    logo: '/clubs/super-lig/goztepe.svg',
    country: 'Turkey',
    league: 'Süper Lig',
    instagramUsername: 'goztepe',

    tiktokUsername: 'goztepesporkulubu',

    twitterUsername: 'Goztepe',
    metrics: {
      instagramFollowers: 360949,
      instagramEngagement: 3.5,
      tiktokFollowers: 7700,
      tiktokViews: 18047450,
      twitterFollowers: 144379,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club47',
    name: 'Sivasspor',
    logo: '/clubs/super-lig/sivasspor.svg',
    country: 'Turkey',
    league: 'Süper Lig',
    instagramUsername: 'sivasspor',
    metrics: {
      instagramFollowers: 221725,
      instagramEngagement: 3.5,
      tiktokFollowers: 66517,
      tiktokViews: 11086250,
      twitterFollowers: 88690,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club48',
    name: 'Konyaspor',
    logo: '/clubs/super-lig/konyaspor.svg',
    country: 'Turkey',
    league: 'Süper Lig',
    instagramUsername: 'konyaspor',

    tiktokUsername: 'konyaspor',

    twitterUsername: 'konyaspor',
    metrics: {
      instagramFollowers: 309857,
      instagramEngagement: 3.5,
      tiktokFollowers: 53321,
      tiktokViews: 15492850,
      twitterFollowers: 123942,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club49',
    name: 'Alanyaspor',
    logo: '/clubs/super-lig/alanyaspor.svg',
    country: 'Turkey',
    league: 'Süper Lig',
    instagramUsername: 'alanyaspor',

    twitterUsername: 'Alanyaspor',
    metrics: {
      instagramFollowers: 114313,
      instagramEngagement: 3.5,
      tiktokFollowers: 5,
      tiktokViews: 5715650,
      twitterFollowers: 45725,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club50',
    name: 'Antalyaspor',
    logo: '/clubs/super-lig/antalyaspor.svg',
    country: 'Turkey',
    league: 'Süper Lig',
    instagramUsername: 'antalyaspor',

    twitterUsername: 'Antalyaspor',
    metrics: {
      instagramFollowers: 182218,
      instagramEngagement: 3.5,
      tiktokFollowers: 23,
      tiktokViews: 9110900,
      twitterFollowers: 72887,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club51',
    name: 'Gaziantep FK',
    logo: '/clubs/super-lig/gaziantepfk.svg',
    country: 'Turkey',
    league: 'Süper Lig',
    instagramUsername: 'gaziantepfk',

    twitterUsername: 'GaziantepFK',
    metrics: {
      instagramFollowers: 218940,
      instagramEngagement: 3.5,
      tiktokFollowers: 3,
      tiktokViews: 10947000,
      twitterFollowers: 87576,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club52',
    name: 'Kasımpaşa',
    logo: '/clubs/super-lig/kasimpasask.svg',
    country: 'Turkey',
    league: 'Süper Lig',
    instagramUsername: 'kasimpasask',

    twitterUsername: 'KasimpasaSK',
    metrics: {
      instagramFollowers: 92564,
      instagramEngagement: 3.5,
      tiktokFollowers: 222,
      tiktokViews: 4628200,
      twitterFollowers: 37025,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club53',
    name: 'Hatayspor',
    logo: '/clubs/super-lig/hatayspor.svg',
    country: 'Turkey',
    league: 'Süper Lig',
    instagramUsername: 'hatayspor',
    metrics: {
      instagramFollowers: 244084,
      instagramEngagement: 3.5,
      tiktokFollowers: 73225,
      tiktokViews: 12204200,
      twitterFollowers: 97633,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club54',
    name: 'Pendikspor',
    logo: '/clubs/super-lig/pendikspor.svg',
    country: 'Turkey',
    league: 'Süper Lig',
    instagramUsername: 'pendikspor',
    metrics: {
      instagramFollowers: 64557,
      instagramEngagement: 3.5,
      tiktokFollowers: 19367,
      tiktokViews: 3227850,
      twitterFollowers: 25822,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club55',
    name: 'Kayserispor',
    logo: '/clubs/super-lig/kayserisporfk.svg',
    country: 'Turkey',
    league: 'Süper Lig',
    instagramUsername: 'kayserisporfk',
    metrics: {
      instagramFollowers: 193333,
      instagramEngagement: 3.5,
      tiktokFollowers: 3,
      tiktokViews: 9666650,
      twitterFollowers: 77333,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club56',
    name: 'Eyüpspor',
    logo: '/clubs/super-lig/eyupsporkulubu.svg',
    country: 'Turkey',
    league: 'Süper Lig',
    instagramUsername: 'eyupsporkulubu',
    metrics: {
      instagramFollowers: 186374,
      instagramEngagement: 3.5,
      tiktokFollowers: 231,
      tiktokViews: 9318700,
      twitterFollowers: 74549,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club57',
    name: 'Çaykur Rizespor',
    logo: '/clubs/super-lig/crizesporas.svg',
    country: 'Turkey',
    league: 'Süper Lig',
    instagramUsername: 'crizesporas',
    metrics: {
      instagramFollowers: 158572,
      instagramEngagement: 3.5,
      tiktokFollowers: 3412,
      tiktokViews: 7928600,
      twitterFollowers: 63428,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  // Serie A
  {
    id: 'club58',
    name: 'Juventus',
    logo: '/clubs/serie-a/juventus.svg',
    country: 'Italy',
    league: 'Serie A',
    instagramUsername: 'juventus',

    tiktokUsername: 'juventus',

    twitterUsername: 'juventusfc',
    metrics: {
      instagramFollowers: 59850754,
      instagramEngagement: 2.5,
      tiktokFollowers: 41825618,
      tiktokViews: 2992537700,
      twitterFollowers: 23940301,
      twitterEngagement: 2.0,
    },
    digitalScore: 0,
  },
  {
    id: 'club59',
    name: 'AC Milan',
    logo: '/clubs/serie-a/acmilan.svg',
    country: 'Italy',
    league: 'Serie A',
    instagramUsername: 'acmilan',

    tiktokUsername: 'acmilan',

    twitterUsername: 'acmilan',
    metrics: {
      instagramFollowers: 18169547,
      instagramEngagement: 2.5,
      tiktokFollowers: 22761795,
      tiktokViews: 908477350,
      twitterFollowers: 7267818,
      twitterEngagement: 2.0,
    },
    digitalScore: 0,
  },
  {
    id: 'club60',
    name: 'Inter Milan',
    logo: '/clubs/serie-a/inter.svg',
    country: 'Italy',
    league: 'Serie A',
    instagramUsername: 'inter',

    tiktokUsername: 'inter',

    twitterUsername: 'Inter',
    metrics: {
      instagramFollowers: 14373076,
      instagramEngagement: 2.5,
      tiktokFollowers: 17896838,
      tiktokViews: 718653800,
      twitterFollowers: 5749230,
      twitterEngagement: 2.0,
    },
    digitalScore: 0,
  },
  {
    id: 'club61',
    name: 'SSC Napoli',
    logo: '/clubs/serie-a/officialsscnapoli.svg',
    country: 'Italy',
    league: 'Serie A',
    instagramUsername: 'officialsscnapoli',
    metrics: {
      instagramFollowers: 5271587,
      instagramEngagement: 3.0,
      tiktokFollowers: 1581476,
      tiktokViews: 263579350,
      twitterFollowers: 2108634,
      twitterEngagement: 2.4,
    },
    digitalScore: 0,
  },
  {
    id: 'club62',
    name: 'AS Roma',
    logo: '/clubs/serie-a/officialasroma.svg',
    country: 'Italy',
    league: 'Serie A',
    instagramUsername: 'officialasroma',
    metrics: {
      instagramFollowers: 7327703,
      instagramEngagement: 3.0,
      tiktokFollowers: 1117,
      tiktokViews: 366385150,
      twitterFollowers: 2931081,
      twitterEngagement: 2.4,
    },
    digitalScore: 0,
  },
  {
    id: 'club63',
    name: 'ACF Fiorentina',
    logo: '/clubs/serie-a/acffiorentina.svg',
    country: 'Italy',
    league: 'Serie A',
    instagramUsername: 'acffiorentina',

    tiktokUsername: 'acffiorentina',

    twitterUsername: 'acffiorentina',
    metrics: {
      instagramFollowers: 1433220,
      instagramEngagement: 3.0,
      tiktokFollowers: 1150697,
      tiktokViews: 71661000,
      twitterFollowers: 573288,
      twitterEngagement: 2.4,
    },
    digitalScore: 0,
  },
  {
    id: 'club64',
    name: 'SS Lazio',
    logo: '/clubs/serie-a/official_sslazio.svg',
    country: 'Italy',
    league: 'Serie A',
    instagramUsername: 'official_sslazio',
    metrics: {
      instagramFollowers: 1204918,
      instagramEngagement: 3.0,
      tiktokFollowers: 997,
      tiktokViews: 60245900,
      twitterFollowers: 481967,
      twitterEngagement: 2.4,
    },
    digitalScore: 0,
  },
  {
    id: 'club65',
    name: 'Atalanta BC',
    logo: '/clubs/serie-a/atalantabc.svg',
    country: 'Italy',
    league: 'Serie A',
    instagramUsername: 'atalantabc',

    tiktokUsername: 'atalanta_be',

    twitterUsername: 'Atalanta_BC',
    metrics: {
      instagramFollowers: 1180389,
      instagramEngagement: 3.0,
      tiktokFollowers: 1200000,
      tiktokViews: 59019450,
      twitterFollowers: 472155,
      twitterEngagement: 2.4,
    },
    digitalScore: 0,
  },
  {
    id: 'club66',
    name: 'Como 1907',
    logo: '/clubs/serie-a/comofootball.svg',
    country: 'Italy',
    league: 'Serie A',
    instagramUsername: 'comofootball',
    metrics: {
      instagramFollowers: 1057651,
      instagramEngagement: 3.0,
      tiktokFollowers: 6,
      tiktokViews: 52882550,
      twitterFollowers: 423060,
      twitterEngagement: 2.4,
    },
    digitalScore: 0,
  },
  {
    id: 'club67',
    name: 'Parma Calcio',
    logo: '/clubs/serie-a/parmacalcio1913.svg',
    country: 'Italy',
    league: 'Serie A',
    instagramUsername: 'parmacalcio1913',

    tiktokUsername: 'parmacalcio1913',

    twitterUsername: '1913parmacalcio',
    metrics: {
      instagramFollowers: 709973,
      instagramEngagement: 3.5,
      tiktokFollowers: 1512979,
      tiktokViews: 35498650,
      twitterFollowers: 283989,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club68',
    name: 'Bologna FC',
    logo: '/clubs/serie-a/bolognafc1909.svg',
    country: 'Italy',
    league: 'Serie A',
    instagramUsername: 'bolognafc1909',

    tiktokUsername: 'bolobolognafootballclub',

    twitterUsername: 'BfcOfficialPage',
    metrics: {
      instagramFollowers: 620878,
      instagramEngagement: 3.5,
      tiktokFollowers: 615400,
      tiktokViews: 31043900,
      twitterFollowers: 248351,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club69',
    name: 'Cagliari Calcio',
    logo: '/clubs/serie-a/cagliaricalcio.svg',
    country: 'Italy',
    league: 'Serie A',
    instagramUsername: 'cagliaricalcio',

    tiktokUsername: 'cagliaricalcio',

    twitterUsername: 'CagliariCalcio',
    metrics: {
      instagramFollowers: 541973,
      instagramEngagement: 3.5,
      tiktokFollowers: 363899,
      tiktokViews: 27098650,
      twitterFollowers: 216789,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club70',
    name: 'Torino FC',
    logo: '/clubs/serie-a/torinofc1906.svg',
    country: 'Italy',
    league: 'Serie A',
    instagramUsername: 'torinofc1906',
    metrics: {
      instagramFollowers: 494786,
      instagramEngagement: 3.5,
      tiktokFollowers: 328308,
      tiktokViews: 24739300,
      twitterFollowers: 197914,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club71',
    name: 'Genoa CFC',
    logo: '/clubs/serie-a/genoacfc.svg',
    country: 'Italy',
    league: 'Serie A',
    instagramUsername: 'genoacfc',
    metrics: {
      instagramFollowers: 481732,
      instagramEngagement: 3.5,
      tiktokFollowers: 340663,
      tiktokViews: 24086600,
      twitterFollowers: 192692,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club72',
    name: 'Venezia FC',
    logo: '/clubs/serie-a/veneziafc.svg',
    country: 'Italy',
    league: 'Serie A',
    instagramUsername: 'veneziafc',
    metrics: {
      instagramFollowers: 437627,
      instagramEngagement: 3.5,
      tiktokFollowers: 131288,
      tiktokViews: 21881350,
      twitterFollowers: 175050,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club73',
    name: 'Udinese Calcio',
    logo: '/clubs/serie-a/udinesecalcio.svg',
    country: 'Italy',
    league: 'Serie A',
    instagramUsername: 'udinesecalcio',
    metrics: {
      instagramFollowers: 427490,
      instagramEngagement: 3.5,
      tiktokFollowers: 265442,
      tiktokViews: 21374500,
      twitterFollowers: 170996,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club74',
    name: 'Hellas Verona',
    logo: '/clubs/serie-a/hellasveronafc.svg',
    country: 'Italy',
    league: 'Serie A',
    instagramUsername: 'hellasveronafc',
    metrics: {
      instagramFollowers: 326338,
      instagramEngagement: 3.5,
      tiktokFollowers: 184934,
      tiktokViews: 16316900,
      twitterFollowers: 130535,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club75',
    name: 'AC Monza',
    logo: '/clubs/serie-a/acmonza.svg',
    country: 'Italy',
    league: 'Serie A',
    instagramUsername: 'acmonza',
    metrics: {
      instagramFollowers: 303556,
      instagramEngagement: 3.5,
      tiktokFollowers: 91066,
      tiktokViews: 15177800,
      twitterFollowers: 121422,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club76',
    name: 'US Lecce',
    logo: '/clubs/serie-a/uslecce.svg',
    country: 'Italy',
    league: 'Serie A',
    instagramUsername: 'uslecce',

    tiktokUsername: 'uslecce',

    twitterUsername: 'OfficialUSLecce',
    metrics: {
      instagramFollowers: 249379,
      instagramEngagement: 3.5,
      tiktokFollowers: 36185,
      tiktokViews: 12468950,
      twitterFollowers: 99751,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  // Bundesliga
  {
    id: 'club77',
    name: 'FC Bayern München',
    logo: '/clubs/bundesliga/fcbayern.svg',
    country: 'Germany',
    league: 'Bundesliga',
    instagramUsername: 'fcbayern',

    tiktokUsername: 'fcbayern',

    twitterUsername: 'FCBayern',
    metrics: {
      instagramFollowers: 44015079,
      instagramEngagement: 2.5,
      tiktokFollowers: 26198794,
      tiktokViews: 2200753950,
      twitterFollowers: 17606031,
      twitterEngagement: 2.0,
    },
    digitalScore: 0,
  },
  {
    id: 'club78',
    name: 'Borussia Dortmund',
    logo: '/clubs/bundesliga/bvb09.svg',
    country: 'Germany',
    league: 'Bundesliga',
    instagramUsername: 'bvb09',

    tiktokUsername: 'bvb',

    twitterUsername: 'BVB',
    metrics: {
      instagramFollowers: 20898210,
      instagramEngagement: 2.5,
      tiktokFollowers: 2,
      tiktokViews: 1044910500,
      twitterFollowers: 8359284,
      twitterEngagement: 2.0,
    },
    digitalScore: 0,
  },
  {
    id: 'club79',
    name: 'Bayer 04 Leverkusen',
    logo: '/clubs/bundesliga/bayer04fussball.svg',
    country: 'Germany',
    league: 'Bundesliga',
    instagramUsername: 'bayer04fussball',

    tiktokUsername: 'bayer04',

    twitterUsername: 'bayer04fussball',
    metrics: {
      instagramFollowers: 4648159,
      instagramEngagement: 3.0,
      tiktokFollowers: 10,
      tiktokViews: 232407950,
      twitterFollowers: 1859263,
      twitterEngagement: 2.4,
    },
    digitalScore: 0,
  },
  {
    id: 'club80',
    name: 'RB Leipzig',
    logo: '/clubs/bundesliga/rbleipzig.svg',
    country: 'Germany',
    league: 'Bundesliga',
    instagramUsername: 'rbleipzig',
    metrics: {
      instagramFollowers: 2213347,
      instagramEngagement: 3.0,
      tiktokFollowers: 2914863,
      tiktokViews: 110667350,
      twitterFollowers: 885338,
      twitterEngagement: 2.4,
    },
    digitalScore: 0,
  },
  {
    id: 'club81',
    name: 'Eintracht Frankfurt',
    logo: '/clubs/bundesliga/eintrachtfrankfurt.svg',
    country: 'Germany',
    league: 'Bundesliga',
    instagramUsername: 'eintrachtfrankfurt',
    metrics: {
      instagramFollowers: 1345002,
      instagramEngagement: 3.0,
      tiktokFollowers: 52,
      tiktokViews: 67250100,
      twitterFollowers: 538000,
      twitterEngagement: 2.4,
    },
    digitalScore: 0,
  },
  {
    id: 'club82',
    name: 'Borussia Mönchengladbach',
    logo: '/clubs/bundesliga/borussia.svg',
    country: 'Germany',
    league: 'Bundesliga',
    instagramUsername: 'borussia',

    tiktokUsername: 'borussia',

    twitterUsername: 'borussia',
    metrics: {
      instagramFollowers: 1230443,
      instagramEngagement: 3.0,
      tiktokFollowers: 1378230,
      tiktokViews: 61522150,
      twitterFollowers: 492177,
      twitterEngagement: 2.4,
    },
    digitalScore: 0,
  },
  {
    id: 'club83',
    name: 'VfL Wolfsburg',
    logo: '/clubs/bundesliga/vfl.wolfsburg.svg',
    country: 'Germany',
    league: 'Bundesliga',
    instagramUsername: 'vfl.wolfsburg',
    metrics: {
      instagramFollowers: 926435,
      instagramEngagement: 3.5,
      tiktokFollowers: 277930,
      tiktokViews: 46321750,
      twitterFollowers: 370574,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club84',
    name: 'VfB Stuttgart',
    logo: '/clubs/bundesliga/vfb.svg',
    country: 'Germany',
    league: 'Bundesliga',
    instagramUsername: 'vfb',

    tiktokUsername: 'vfb',

    twitterUsername: 'VfB',
    metrics: {
      instagramFollowers: 706345,
      instagramEngagement: 3.5,
      tiktokFollowers: 211903,
      tiktokViews: 35317250,
      twitterFollowers: 282538,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club85',
    name: 'SC Freiburg',
    logo: '/clubs/bundesliga/scfreiburg.svg',
    country: 'Germany',
    league: 'Bundesliga',
    instagramUsername: 'scfreiburg',

    tiktokUsername: 'scfreiburg',

    twitterUsername: 'scfreiburg',
    metrics: {
      instagramFollowers: 615923,
      instagramEngagement: 3.5,
      tiktokFollowers: 222005,
      tiktokViews: 30796150,
      twitterFollowers: 246369,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club86',
    name: 'SV Werder Bremen',
    logo: '/clubs/bundesliga/werderbremen.svg',
    country: 'Germany',
    league: 'Bundesliga',
    instagramUsername: 'werderbremen',

    tiktokUsername: 'werderbremen',

    twitterUsername: 'werderbremen',
    metrics: {
      instagramFollowers: 577845,
      instagramEngagement: 3.5,
      tiktokFollowers: 265166,
      tiktokViews: 28892250,
      twitterFollowers: 231138,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club87',
    name: 'TSG Hoffenheim',
    logo: '/clubs/bundesliga/tsghoffenheim.svg',
    country: 'Germany',
    league: 'Bundesliga',
    instagramUsername: 'tsghoffenheim',
    metrics: {
      instagramFollowers: 520301,
      instagramEngagement: 3.5,
      tiktokFollowers: 628271,
      tiktokViews: 26015050,
      twitterFollowers: 208120,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club88',
    name: 'FC St. Pauli',
    logo: '/clubs/bundesliga/fcstpauli.svg',
    country: 'Germany',
    league: 'Bundesliga',
    instagramUsername: 'fcstpauli',

    tiktokUsername: 'fcstpauli',

    twitterUsername: 'fcstpauli',
    metrics: {
      instagramFollowers: 454395,
      instagramEngagement: 3.5,
      tiktokFollowers: 82324,
      tiktokViews: 22719750,
      twitterFollowers: 181758,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club89',
    name: '1. FSV Mainz 05',
    logo: '/clubs/bundesliga/1fsvmainz05.svg',
    country: 'Germany',
    league: 'Bundesliga',
    instagramUsername: '1fsvmainz05',
    metrics: {
      instagramFollowers: 337896,
      instagramEngagement: 3.5,
      tiktokFollowers: 662956,
      tiktokViews: 16894800,
      twitterFollowers: 135158,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club90',
    name: 'FC Augsburg',
    logo: '/clubs/bundesliga/fcaugsburg1907.svg',
    country: 'Germany',
    league: 'Bundesliga',
    instagramUsername: 'fcaugsburg1907',
    metrics: {
      instagramFollowers: 277801,
      instagramEngagement: 3.5,
      tiktokFollowers: 32,
      tiktokViews: 13890050,
      twitterFollowers: 111120,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club91',
    name: 'VfL Bochum',
    logo: '/clubs/bundesliga/vflbochum1848.official.svg',
    country: 'Germany',
    league: 'Bundesliga',
    instagramUsername: 'vflbochum1848.official',
    metrics: {
      instagramFollowers: 167610,
      instagramEngagement: 3.5,
      tiktokFollowers: 50283,
      tiktokViews: 8380500,
      twitterFollowers: 67044,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club92',
    name: 'Holstein Kiel',
    logo: '/clubs/bundesliga/holsteinkiel.svg',
    country: 'Germany',
    league: 'Bundesliga',
    instagramUsername: 'holsteinkiel',
    metrics: {
      instagramFollowers: 129679,
      instagramEngagement: 3.5,
      tiktokFollowers: 38903,
      tiktokViews: 6483950,
      twitterFollowers: 51871,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club93',
    name: '1. FC Union Berlin',
    logo: '/clubs/bundesliga/1.fcunion.svg',
    country: 'Germany',
    league: 'Bundesliga',
    instagramUsername: '1.fcunion',
    metrics: {
      instagramFollowers: 342702,
      instagramEngagement: 3.5,
      tiktokFollowers: 102810,
      tiktokViews: 17135100,
      twitterFollowers: 137080,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club94',
    name: '1. FC Heidenheim',
    logo: '/clubs/bundesliga/fch_1846.svg',
    country: 'Germany',
    league: 'Bundesliga',
    instagramUsername: 'fch_1846',
    metrics: {
      instagramFollowers: 98617,
      instagramEngagement: 3.5,
      tiktokFollowers: 29585,
      tiktokViews: 4930850,
      twitterFollowers: 39446,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  // Ligue 1
  {
    id: 'club95',
    name: 'Paris Saint-Germain',
    logo: '/clubs/ligue-1/psg.svg',
    country: 'France',
    league: 'Ligue 1',
    instagramUsername: 'psg',

    tiktokUsername: 'psg',

    twitterUsername: 'PSG_inside',
    metrics: {
      instagramFollowers: 65722865,
      instagramEngagement: 2.5,
      tiktokFollowers: 50685285,
      tiktokViews: 3286143250,
      twitterFollowers: 26289146,
      twitterEngagement: 2.0,
    },
    digitalScore: 0,
  },
  {
    id: 'club96',
    name: 'Olympique de Marseille',
    logo: '/clubs/ligue-1/olympiquedemarseille.svg',
    country: 'France',
    league: 'Ligue 1',
    instagramUsername: 'olympiquedemarseille',

    tiktokUsername: 'om',

    twitterUsername: 'OM_Officiel',
    metrics: {
      instagramFollowers: 3834695,
      instagramEngagement: 3.0,
      tiktokFollowers: 21,
      tiktokViews: 191734750,
      twitterFollowers: 1533878,
      twitterEngagement: 2.4,
    },
    digitalScore: 0,
  },
  {
    id: 'club97',
    name: 'AS Monaco',
    logo: '/clubs/ligue-1/asmonaco.svg',
    country: 'France',
    league: 'Ligue 1',
    instagramUsername: 'asmonaco',

    tiktokUsername: 'asmonaco',

    twitterUsername: 'AS_Monaco',
    metrics: {
      instagramFollowers: 2796573,
      instagramEngagement: 3.0,
      tiktokFollowers: 6991646,
      tiktokViews: 139828650,
      twitterFollowers: 1118629,
      twitterEngagement: 2.4,
    },
    digitalScore: 0,
  },
  {
    id: 'club98',
    name: 'Olympique Lyonnais',
    logo: '/clubs/ligue-1/ol.svg',
    country: 'France',
    league: 'Ligue 1',
    instagramUsername: 'ol',

    tiktokUsername: 'ol_officiel',

    twitterUsername: 'OL',
    metrics: {
      instagramFollowers: 2618444,
      instagramEngagement: 3.0,
      tiktokFollowers: 2300000,
      tiktokViews: 130922200,
      twitterFollowers: 1047377,
      twitterEngagement: 2.4,
    },
    digitalScore: 0,
  },
  {
    id: 'club99',
    name: 'LOSC Lille',
    logo: '/clubs/ligue-1/losclive.svg',
    country: 'France',
    league: 'Ligue 1',
    instagramUsername: 'losclive',
    metrics: {
      instagramFollowers: 1144488,
      instagramEngagement: 3.0,
      tiktokFollowers: 2,
      tiktokViews: 57224400,
      twitterFollowers: 457795,
      twitterEngagement: 2.4,
    },
    digitalScore: 0,
  },
  {
    id: 'club100',
    name: 'OGC Nice',
    logo: '/clubs/ligue-1/ogcnice.svg',
    country: 'France',
    league: 'Ligue 1',
    instagramUsername: 'ogcnice',

    tiktokUsername: 'ogcnice',

    twitterUsername: 'ogcnice',
    metrics: {
      instagramFollowers: 816735,
      instagramEngagement: 3.5,
      tiktokFollowers: 1336179,
      tiktokViews: 40836750,
      twitterFollowers: 326694,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club101',
    name: 'FC Nantes',
    logo: '/clubs/ligue-1/fcnantes.svg',
    country: 'France',
    league: 'Ligue 1',
    instagramUsername: 'fcnantes',

    tiktokUsername: 'fcnantes',

    twitterUsername: 'FCNantes',
    metrics: {
      instagramFollowers: 609335,
      instagramEngagement: 3.5,
      tiktokFollowers: 515774,
      tiktokViews: 30466750,
      twitterFollowers: 243734,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club102',
    name: 'RC Strasbourg',
    logo: '/clubs/ligue-1/rcsa.svg',
    country: 'France',
    league: 'Ligue 1',
    instagramUsername: 'rcsa',
    metrics: {
      instagramFollowers: 590145,
      instagramEngagement: 3.5,
      tiktokFollowers: 1376633,
      tiktokViews: 29507250,
      twitterFollowers: 236058,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club103',
    name: 'RC Lens',
    logo: '/clubs/ligue-1/rclens.svg',
    country: 'France',
    league: 'Ligue 1',
    instagramUsername: 'rclens',

    tiktokUsername: 'rclens',

    twitterUsername: 'RCLens',
    metrics: {
      instagramFollowers: 483036,
      instagramEngagement: 3.5,
      tiktokFollowers: 2015304,
      tiktokViews: 24151800,
      twitterFollowers: 193214,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club104',
    name: 'AS Saint-Étienne',
    logo: '/clubs/ligue-1/asseofficiel.svg',
    country: 'France',
    league: 'Ligue 1',
    instagramUsername: 'asseofficiel',
    metrics: {
      instagramFollowers: 452806,
      instagramEngagement: 3.5,
      tiktokFollowers: 135841,
      tiktokViews: 22640300,
      twitterFollowers: 181122,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club105',
    name: 'Toulouse FC',
    logo: '/clubs/ligue-1/toulousefc.svg',
    country: 'France',
    league: 'Ligue 1',
    instagramUsername: 'toulousefc',

    tiktokUsername: 'toulousefc',

    twitterUsername: 'ToulouseFC',
    metrics: {
      instagramFollowers: 451910,
      instagramEngagement: 3.5,
      tiktokFollowers: 875126,
      tiktokViews: 22595500,
      twitterFollowers: 180764,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club106',
    name: 'Le Havre AC',
    logo: '/clubs/ligue-1/hac_foot.svg',
    country: 'France',
    league: 'Ligue 1',
    instagramUsername: 'hac_foot',
    metrics: {
      instagramFollowers: 168331,
      instagramEngagement: 3.5,
      tiktokFollowers: 50499,
      tiktokViews: 8416550,
      twitterFollowers: 67332,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club107',
    name: 'Stade Rennais',
    logo: '/clubs/ligue-1/staderennaisfc.svg',
    country: 'France',
    league: 'Ligue 1',
    instagramUsername: 'staderennaisfc',

    tiktokUsername: 'staderennaisfc',

    twitterUsername: 'staderennais',
    metrics: {
      instagramFollowers: 640645,
      instagramEngagement: 3.5,
      tiktokFollowers: 1245082,
      tiktokViews: 32032250,
      twitterFollowers: 256258,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club108',
    name: 'Stade Brestois',
    logo: '/clubs/ligue-1/stadebrestois29.svg',
    country: 'France',
    league: 'Ligue 1',
    instagramUsername: 'stadebrestois29',
    metrics: {
      instagramFollowers: 392638,
      instagramEngagement: 3.5,
      tiktokFollowers: 14,
      tiktokViews: 19631900,
      twitterFollowers: 157055,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club109',
    name: 'Angers SCO',
    logo: '/clubs/ligue-1/angers_sco.svg',
    country: 'France',
    league: 'Ligue 1',
    instagramUsername: 'angers_sco',
    metrics: {
      instagramFollowers: 185950,
      instagramEngagement: 3.5,
      tiktokFollowers: 94,
      tiktokViews: 9297500,
      twitterFollowers: 74380,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
  {
    id: 'club110',
    name: 'AJ Auxerre',
    logo: '/clubs/ligue-1/aja.svg',
    country: 'France',
    league: 'Ligue 1',
    instagramUsername: 'aja',
    metrics: {
      instagramFollowers: 165448,
      instagramEngagement: 3.5,
      tiktokFollowers: 49634,
      tiktokViews: 8272400,
      twitterFollowers: 66179,
      twitterEngagement: 2.8,
    },
    digitalScore: 0,
  },
];

// Calculate digital scores
CLUB_DATA.forEach((club) => {
  const m = club.metrics;
  club.digitalScore = Math.round(
    (m.instagramFollowers / 1000000) * 10 + m.instagramEngagement * 5 +
    (m.tiktokFollowers / 1000000) * 8 + (m.tiktokViews / 100000000) * 6 +
    (m.twitterFollowers / 1000000) * 7 + m.twitterEngagement * 4
  );
});